version: 2.1
orbs:
  node: circleci/node@1.1.6
  gcp-gke: circleci/gcp-gke@1.0.4
  gcp-gcr: circleci/gcp-gcr@0.7.1
workflows:
  build-app:
    jobs:
      - build:
          context: Google
      - build-and-push:
          context: Google
          requires:
            - build
    
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install
      - node/install-npm
      - node/with-cache:
            steps:
              - run: npm install
            cache-key: package.json
            use-strict-cache: true
  build-and-push:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: orb-test
          registry-url: eu.gcr.io
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: orb-test
          registry-url: eu.gcr.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
