version: 2.1
orbs:
  node: circleci/node@1.1.6
  gcp-gke: circleci/gcp-gke@1.0.4
  gcr: circleci/gcp-gcr@0.7.1
workflows:
  build:
    jobs:
      - build:
          context: Google
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install
      - node/install-npm
      - node/with-cache:
            steps:
              - run: npm install
            cache-key: package.json
            use-strict-cache: true
