version: 2.1
orbs:
  node: circleci/node@3.0.1
  gcp-gke: circleci/gcp-gke@1.0.4
  gcr: circleci/gcp-gcr@0.7.1
workflows:
  build:
    jobs:
      - build:
          context: Google
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - run: echo $GOOGLE_COMPUTE_ZONE